=== nellen/ch.bfh.bti7054.w2014.q.Web-Prophecies/Web-Phrophecies/src/huber3/menus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<!-- Defining simple elements -->
	<xsd:element name="text" type="xsd:string" default="Value not set"/>
	<xsd:element name="enabled" type="xsd:boolean" default="1" />
	
	<!-- Defining attributes -->
	<xsd:attribute name="itemName">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="([A-Z])*" />
				<xsd:whiteSpace value="collapse" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	
	<xsd:attribute name="menuName">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="([a-zA-Z])*" />
				<xsd:whiteSpace value="collapse" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:attribute>
	
	
	<!-- Defining complex elements -->
	<xsd:element name="siteName" default="main">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[a-z]([a-zA-Z0-9_])*" />
				<xsd:whiteSpace value="collapse" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>
	
	<xsd:element name="subItem">
		<xsd:complexType mixed="true">
			<xsd:all>
				<xsd:element ref="text" />
				<xsd:element ref="siteName" />
				<xsd:element ref="enabled" />
				<xsd:element ref="subMenu" maxOccurs="1" minOccurs="0"/>
			</xsd:all>
			<xsd:attribute ref="itemName" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="subMenu">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="subItem" maxOccurs="unbounded" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="menuItem">
		<xsd:complexType mixed="true">
			<xsd:all>
				<xsd:element ref="text" />
				<xsd:element ref="siteName" />
				<xsd:element ref="enabled" />
				<xsd:element ref="subMenu" minOccurs="0" />
			</xsd:all>
			<xsd:attribute ref="itemName" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="menu">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:element ref="menuItem" maxOccurs="unbounded" minOccurs="1" />
			</xsd:sequence>
			<xsd:attribute ref="menuName" use="required"/>
		</xsd:complexType>
	</xsd:element>	
	
	<xsd:element name="menus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="menu" maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== nellen/ch.bfh.bti7054.w2014.q.Web-Prophecies/Web-Phrophecies/src/includes/menus.xml
<?xml version="1.0" encoding="UTF-8"?>

<menus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="./includes/menus.xsd">
	<menu menuName="mainMenu">
	
		<menuItem itemName="HOME">
			<text>Home</text>
			<siteName>main</siteName>
			<enabled>1</enabled>
		</menuItem>
		
		<menuItem itemName="SHOP">
			<text>Shop</text>
			<siteName>shop</siteName>
			<enabled>1</enabled>
			<subMenu>
				<subItem itemName="FOOD">
					<text>Food</text>
					<siteName>food</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="BEVERAGE">
					<text>Beverage</text>
					<siteName>beverage</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="MENU">
					<text>Menu</text>
					<siteName>menu</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="SPECIALS">
					<text>Specials</text>
					<siteName>specials</siteName>
					<enabled>1</enabled>
				</subItem>
			</subMenu>
		</menuItem>
		
		<menuItem itemName="ABOUTUS">
			<text>About us</text>
			<siteName>aboutus</siteName>
			<enabled>1</enabled>
		</menuItem>
		
		<menuItem itemName="CONTACT">
			<text>Contact</text>
			<siteName>contact</siteName>
			<enabled>1</enabled>
		</menuItem>
	</menu>
	
	<menu menuName="userMenu">
	
		<menuItem itemName="LOGIN">
			<text>Login / User Menu</text>
			<siteName>login_User</siteName>
			<enabled>1</enabled>
			<subMenu>
				<subItem itemName="BASKET">
					<text>Basket</text>
					<siteName>basket</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="USERPROFILE">
					<text>Userprofile</text>
					<siteName>userprofile</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="FILLER">
					<text>. . .</text>
					<siteName>filler</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="CHECKOUT">
					<text>Checkout</text>
					<siteName>checkout</siteName>
					<enabled>1</enabled>
				</subItem>
				<subItem itemName="ADMINISTRATION">
					<text>Administration</text>
					<siteName>administration</siteName>
					<enabled>1</enabled>
				</subItem>
			</subMenu>
		</menuItem>
		
	</menu>

</menus>
